
# This file is automatically generated, you probably don't want to edit this

wordcountOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "wordcountOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            textVar = NULL,
            lexiconSource = "builder",
            lexicon = list(
                list(category="Positivity", terms="very, good, happy, amazing"),
                list(category="Negations", terms="not, non, never, no, niente"),
                list(category="Modality", terms="can*, could*, might*, may*, should*")),
            dictionary = "very:Intensifiers; not:Negations; can*:Modal_Expressions",
            detectedWords = FALSE, ...) {

            super$initialize(
                package="wowordcount",
                name="wordcount",
                requiresData=TRUE,
                ...)

            private$..textVar <- jmvcore::OptionVariable$new(
                "textVar",
                textVar,
                permitted=list(
                    "id",
                    "factor"))
            private$..lexiconSource <- jmvcore::OptionList$new(
                "lexiconSource",
                lexiconSource,
                options=list(
                    "builder",
                    "paste"),
                default="builder")
            private$..lexicon <- jmvcore::OptionArray$new(
                "lexicon",
                lexicon,
                default=list(
                    list(category="Positivity", terms="very, good, happy, amazing"),
                    list(category="Negations", terms="not, non, never, no, niente"),
                    list(category="Modality", terms="can*, could*, might*, may*, should*")),
                template=jmvcore::OptionGroup$new(
                    "lexicon",
                    NULL,
                    elements=list(
                        jmvcore::OptionString$new(
                            "category",
                            NULL),
                        jmvcore::OptionString$new(
                            "terms",
                            NULL))))
            private$..dictionary <- jmvcore::OptionString$new(
                "dictionary",
                dictionary,
                default="very:Intensifiers; not:Negations; can*:Modal_Expressions")
            private$..detectedWords <- jmvcore::OptionBool$new(
                "detectedWords",
                detectedWords,
                default=FALSE)
            private$..saveResults <- jmvcore::OptionOutput$new(
                "saveResults")

            self$.addOption(private$..textVar)
            self$.addOption(private$..lexiconSource)
            self$.addOption(private$..lexicon)
            self$.addOption(private$..dictionary)
            self$.addOption(private$..detectedWords)
            self$.addOption(private$..saveResults)
        }),
    active = list(
        textVar = function() private$..textVar$value,
        lexiconSource = function() private$..lexiconSource$value,
        lexicon = function() private$..lexicon$value,
        dictionary = function() private$..dictionary$value,
        detectedWords = function() private$..detectedWords$value,
        saveResults = function() private$..saveResults$value),
    private = list(
        ..textVar = NA,
        ..lexiconSource = NA,
        ..lexicon = NA,
        ..dictionary = NA,
        ..detectedWords = NA,
        ..saveResults = NA)
)

wordcountResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "wordcountResults",
    inherit = jmvcore::Group,
    active = list(
        dictSummary = function() private$.items[["dictSummary"]],
        statusNote = function() private$.items[["statusNote"]],
        savedResults = function() private$.items[["savedResults"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Word Count (LIWC-style)")
            self$add(jmvcore::Table$new(
                options=options,
                name="dictSummary",
                title="Dictionary Summary",
                rows=0,
                columns=list(
                    list(
                        `name`="category", 
                        `title`="Category", 
                        `type`="text"),
                    list(
                        `name`="exactTerms", 
                        `title`="Exact Terms", 
                        `type`="integer"),
                    list(
                        `name`="wildcardPrefixes", 
                        `title`="Wildcard Prefixes", 
                        `type`="integer"),
                    list(
                        `name`="multiWordTerms", 
                        `title`="Multi-word Terms", 
                        `type`="integer"))))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="statusNote",
                title="Status",
                visible=FALSE))
            self$add(jmvcore::Output$new(
                options=options,
                name="savedResults",
                title="Add results to spreadsheet",
                items="(0)",
                varTitle="`Word Count result`",
                measureType="continuous"))}))

wordcountBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "wordcountBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "wowordcount",
                name = "wordcount",
                version = c(0,1,0),
                options = options,
                results = wordcountResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' Word Count (LIWC-style)
#'
#' 
#' @param data .
#' @param textVar .
#' @param lexiconSource Where the dictionary comes from. Exactly one source is
#'   used: \code{builder} counts with the categories defined in the lexicon
#'   builder below; \code{paste} counts with the wordlist pasted in the paste
#'   box.
#' @param lexicon Lexicon rows built in the UI: one category per row with its
#'   terms as a comma-separated list. A trailing * marks a prefix wildcard;
#'   multi-word terms are allowed. The default rows are a working example: edit
#'   or remove them. Only used when the lexicon source is set to \code{Build in
#'   the app}.
#' @param dictionary Paste your wordlist. Two formats are accepted: 1) TSV
#'   with a DicTerm header (multi-line), or 2) single-line flat format:
#'   very:Intensifiers; not:Negations; can*:Modal_Expressions Only used when the
#'   lexicon source is set to \code{Paste a dictionary}.
#' @param detectedWords .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$dictSummary} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$statusNote} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$savedResults} \tab \tab \tab \tab \tab an output \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$dictSummary$asDF}
#'
#' \code{as.data.frame(results$dictSummary)}
#'
#' @export
wordcount <- function(
    data,
    textVar,
    lexiconSource = "builder",
    lexicon = list(
                list(category="Positivity", terms="very, good, happy, amazing"),
                list(category="Negations", terms="not, non, never, no, niente"),
                list(category="Modality", terms="can*, could*, might*, may*, should*")),
    dictionary = "very:Intensifiers; not:Negations; can*:Modal_Expressions",
    detectedWords = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("wordcount requires jmvcore to be installed (restart may be required)")

    if ( ! missing(textVar)) textVar <- jmvcore::resolveQuo(jmvcore::enquo(textVar))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(textVar), textVar, NULL))


    options <- wordcountOptions$new(
        textVar = textVar,
        lexiconSource = lexiconSource,
        lexicon = lexicon,
        dictionary = dictionary,
        detectedWords = detectedWords)

    analysis <- wordcountClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

