
# This file is automatically generated, you probably don't want to edit this

wordcountOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "wordcountOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            textVar = NULL,
            lexicon = list(
                list(category="Positivity", terms="very, good, happy, amazing"),
                list(category="Negations", terms="not, non, never, no, niente"),
                list(category="Modality", terms="can*, could*, might*, may*, should*")),
            detectedWords = FALSE, ...) {

            super$initialize(
                package="wowordcount",
                name="wordcount",
                requiresData=TRUE,
                ...)

            private$..textVar <- jmvcore::OptionVariable$new(
                "textVar",
                textVar,
                permitted=list(
                    "id",
                    "factor"))
            private$..lexicon <- jmvcore::OptionArray$new(
                "lexicon",
                lexicon,
                default=list(
                    list(category="Positivity", terms="very, good, happy, amazing"),
                    list(category="Negations", terms="not, non, never, no, niente"),
                    list(category="Modality", terms="can*, could*, might*, may*, should*")),
                template=jmvcore::OptionGroup$new(
                    "lexicon",
                    NULL,
                    elements=list(
                        jmvcore::OptionString$new(
                            "category",
                            NULL),
                        jmvcore::OptionString$new(
                            "terms",
                            NULL))))
            private$..detectedWords <- jmvcore::OptionBool$new(
                "detectedWords",
                detectedWords,
                default=FALSE)
            private$..saveResults <- jmvcore::OptionOutput$new(
                "saveResults")

            self$.addOption(private$..textVar)
            self$.addOption(private$..lexicon)
            self$.addOption(private$..detectedWords)
            self$.addOption(private$..saveResults)
        }),
    active = list(
        textVar = function() private$..textVar$value,
        lexicon = function() private$..lexicon$value,
        detectedWords = function() private$..detectedWords$value,
        saveResults = function() private$..saveResults$value),
    private = list(
        ..textVar = NA,
        ..lexicon = NA,
        ..detectedWords = NA,
        ..saveResults = NA)
)

wordcountResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "wordcountResults",
    inherit = jmvcore::Group,
    active = list(
        dictSummary = function() private$.items[["dictSummary"]],
        catSummary = function() private$.items[["catSummary"]],
        statusNote = function() private$.items[["statusNote"]],
        saveResults = function() private$.items[["saveResults"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Word Count (LIWC-style)")
            self$add(jmvcore::Table$new(
                options=options,
                name="dictSummary",
                title="Dictionary Summary",
                rows=0,
                clearWith=list(
                    "textVar",
                    "lexicon"),
                columns=list(
                    list(
                        `name`="category", 
                        `title`="Category", 
                        `type`="text"),
                    list(
                        `name`="exactTerms", 
                        `title`="Exact Terms", 
                        `type`="integer"),
                    list(
                        `name`="wildcardPrefixes", 
                        `title`="Wildcard Prefixes", 
                        `type`="integer"),
                    list(
                        `name`="multiWordTerms", 
                        `title`="Multi-word Terms", 
                        `type`="integer"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="catSummary",
                title="Category Counts Summary",
                rows=0,
                clearWith=list(
                    "textVar",
                    "lexicon"),
                columns=list(
                    list(
                        `name`="category", 
                        `title`="Category", 
                        `type`="text"),
                    list(
                        `name`="totalCount", 
                        `title`="Total Matches", 
                        `type`="integer"),
                    list(
                        `name`="meanCount", 
                        `title`="Mean / Doc", 
                        `type`="number"),
                    list(
                        `name`="meanPerc", 
                        `title`="Mean % of Tokens", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="docCount", 
                        `title`="Docs with Matches", 
                        `type`="integer"),
                    list(
                        `name`="docPerc", 
                        `title`="% of Docs", 
                        `type`="number", 
                        `format`="zto"))))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="statusNote",
                title="Status",
                visible=FALSE,
                clearWith=list(
                    "textVar",
                    "lexicon")))
            self$add(jmvcore::Output$new(
                options=options,
                name="saveResults",
                title="Append results to the data set",
                initInRun=TRUE,
                clearWith=list(
                    "textVar",
                    "lexicon",
                    "detectedWords")))}))

wordcountBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "wordcountBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "wowordcount",
                name = "wordcount",
                version = c(1,0,0),
                options = options,
                results = wordcountResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' Word Count (LIWC-style)
#'
#' 
#' @param data .
#' @param textVar .
#' @param lexicon One category per row with its terms as a comma-separated
#'   list. A trailing * marks a prefix wildcard; multi-word terms are allowed.
#'   The default rows are a working example: edit or remove them.
#' @param detectedWords .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$dictSummary} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$catSummary} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$statusNote} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$saveResults} \tab \tab \tab \tab \tab an output \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$dictSummary$asDF}
#'
#' \code{as.data.frame(results$dictSummary)}
#'
#' @export
wordcount <- function(
    data,
    textVar,
    lexicon = list(
                list(category="Positivity", terms="very, good, happy, amazing"),
                list(category="Negations", terms="not, non, never, no, niente"),
                list(category="Modality", terms="can*, could*, might*, may*, should*")),
    detectedWords = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("wordcount requires jmvcore to be installed (restart may be required)")

    if ( ! missing(textVar)) textVar <- jmvcore::resolveQuo(jmvcore::enquo(textVar))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(textVar), textVar, NULL))


    options <- wordcountOptions$new(
        textVar = textVar,
        lexicon = lexicon,
        detectedWords = detectedWords)

    analysis <- wordcountClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

